///
/// Boundary class for a User object, implemented from Firebase
/// @authors Spencer Hoag & Zachary Hudelson
/// @version 1.0
class MyUser {

  late final String uid;
  late String username;

  /// User Objects
  /// @param uid User ID generated by firebase
  /// @param username Username of a User
  MyUser({required this.uid, required this.username});



  Map<String, dynamic> toMap() {
    return {
      'uid': uid,
      'username': username,
    };
  }

  factory MyUser.fromMap(Map<String, dynamic> map) {
    return MyUser(uid: map['uid'], username: map['username']);
  }

}