// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKD-JeHi3Zce5q-woEN1h78bvwuAZWMpM',
    appId: '1:77310885014:web:4bb296afcb7924673056b7',
    messagingSenderId: '77310885014',
    projectId: 'motilist-b7aab',
    authDomain: 'motilist-b7aab.firebaseapp.com',
    storageBucket: 'motilist-b7aab.appspot.com',
    measurementId: 'G-SVSSEM5HX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyEyv5sw-6fQJgq_ND004nL9VhLNMd4A4',
    appId: '1:77310885014:android:ca471ca96299b1f23056b7',
    messagingSenderId: '77310885014',
    projectId: 'motilist-b7aab',
    storageBucket: 'motilist-b7aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo8-7QDLt7C3s0z81fYGw0lZfPiSNj0xg',
    appId: '1:77310885014:ios:389792daa450febe3056b7',
    messagingSenderId: '77310885014',
    projectId: 'motilist-b7aab',
    storageBucket: 'motilist-b7aab.appspot.com',
    iosBundleId: 'com.example.testmoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo8-7QDLt7C3s0z81fYGw0lZfPiSNj0xg',
    appId: '1:77310885014:ios:92235c3354dc744a3056b7',
    messagingSenderId: '77310885014',
    projectId: 'motilist-b7aab',
    storageBucket: 'motilist-b7aab.appspot.com',
    iosBundleId: 'com.example.testmoti.RunnerTests',
  );
}
